<link type="text/css" href="${pageContext.request.contextPath}/resources/css/car-info.css" rel="stylesheet"/>		
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/main-style.css" rel="stylesheet"/>
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/tiles-style.css" rel="stylesheet"/>
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/dpopdown-menu.css" rel="stylesheet"/>	
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/edit-page-style.css" rel="stylesheet"/>
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/profile-and-edit-style.css" rel="stylesheet"/>		
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/admin-page-style.css" rel="stylesheet"/>		
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/all-cars.css" rel="stylesheet"/>		
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/table-style.css" rel="stylesheet"/>		
<link type="text/css" href="${pageContext.request.contextPath}/resources/css/car-rent.css" rel="stylesheet"/>
